### ISSUE TITLE
Publish to nimble

### ISSUE THREAD

**Issue by Nycto** [samdze/playdate-nim#1]
Are there any plans to make this repo available as a nimble module?

I know there are some specific build configurations required to allow a module to build, but I think those can also be vended.

Cheers!

**Comment by Nycto** [comment]
I should add: I'm definitely willing to contribute to make this happen, but I wanted to check if you’re interested first

**Comment by samdze** [comment]
Yes! There are plans to publish it when the package is stable enough.

As you said however, a specific build configuration has to be used, and I'm not sure it is possible to conveniently "import" and use it as part of the module.

Let me know if you have more info or a solution to this.

Making this a module that you can install and then just works would be awesome!

**Comment by Nycto** [comment]
It can't be a total "install and go", but I think I've got it as hands off as possible:

https://github.com/Nycto/playdate-nim

After a `nimble install`, users need to define a bare bones `config.nims`:

https://github.com/Nycto/playdate-nim/blob/main/playdate_example/config.nims#L1

And add an `include` to the nimble file:

https://github.com/Nycto/playdate-nim/blob/main/playdate_example/playdate_example.nimble#L14

My implementation is still a prototype, but it's enough compile the code and run the simulator. 

To get the build targets working in `nimble`, I moved the logic into an includable file:

https://github.com/Nycto/playdate-nim/blob/main/src/playdate/build.nim#L83-L96

You can also see the includable `config.nim` here:

https://github.com/Nycto/playdate-nim/blob/main/src/playdate/config.nim

It's also worth noting that I moved some of the environment variable definitions into the nimble tasks instead:

https://github.com/Nycto/playdate-nim/blob/main/src/playdate/build.nim#L72-L75

**Comment by samdze** [comment]
Alright, I think you're on the right path, an include statement should be perfectly fine.
I was trying to see if there's a way to make Nimble execute a package install-time script but I didn't find anything as yet.

Also defining the project name, author and other variables dynamically in Nim is the way to go.

Feel free to make a PR when you think you're ready, I'll progressively make adjustments (if needed) and then publish the package!

**Comment by Nycto** [comment]
Sounds good. It might take me a day or two, but I'll clean this up and submit a PR
