### ISSUE TITLE
api aliases

### ISSUE THREAD

**Issue by ninovanhooff** [samdze/playdate-nim#23]
In lua, it's common to alias the api's like gfx = playdate.graphics. 

In nim, `playdate` isn't initialised yet when top-level code is executed. What is an efficient and safe way to do this?

I found that `proc gfx(): ptr PlaydateGraphics = playdate.graphics`

works, at least. But it's a shame it is evaluated on every usage.

So I guess

```
var gfx: ptr PlaydateGraphics

proc init() =
  gfx = playdate.graphics

```

Would be the way to go, although it has the requirement of no access to gfx before init is called?

**Comment by ninovanhooff** [comment]
My question here being: what is the recommended / most canonical way of writing a shorthand for playdate.graphics?

**Comment by samdze** [comment]
The way you're suggesting is one of the best ways I guess.
Sure, having to manually initialize a global variable is not ideal.

Another good way to create shorthands is by using templates:
```nim
template gfx: untyped = playdate.graphics
```

Should be more performant than using functions.
