### ISSUE TITLE
implement os module

### ISSUE THREAD

**Issue by ninovanhooff** [samdze/playdate-nim#24]
import os

sleep(1000)

Gives a OS module not ported to your operating system error

**Comment by samdze** [comment]
I don't think `std/os` can be implemented at all.
It requires an underlying os that provides low level system calls, but on the Playdate we only have the SDK API.

**Comment by ninovanhooff** [comment]
Allright, I don't think it is essential. Developers will just have to compare current time to wake-up time and early-exit in the update loop until enough time passed
