### ISSUE TITLE
Unclear naming requirement for main entrypoint nim file

### ISSUE THREAD

**Issue by ninovanhooff** [samdze/playdate-nim#37]
I adopted the sample project, and it took me some trial and error to find out what the naming requirements were for various parts.

My project is called **wheeelsprung**

I was unaware that the name of the nimble file defines the project name, and that there exists a requirement for that to match the value of `bin` in that nimble file.

At some point I used `main.nim` as the entrypoint for my game and also used 

wheelsprung.nimble
```
bin           = @["main"]
```

accordingly. I then had some file not found errors. When changing `main` to `wheelsprung` everywhere to match  `wheelsprung.nimble`, the problem was resolved.

Perhaps, I would not have run into this problem when starting from scratch (`nim setup`).

My suggestion: add a comment to the example .nimble file:

```
## the main entrypoint of your game. In this example the file `<project root>/src/playdate_example.nim` is
## the first nim file that is executed when the game is started
srcDir        = "src"
bin           = @["playdate_example"]
```

**Comment by samdze** [comment]
Yeah the name of the bin has to match the name of the project, it is not a Playdate bindings specific requirement.
It is always initialized this way when you create a new Nim package with `nimble init`, but I'm ok adding a comment.

**Comment by ninovanhooff** [comment]
https://github.com/samdze/playdate-nim/pull/39
