### ISSUE TITLE
dev should be the default branch

### ISSUE THREAD

**Issue by ninovanhooff** [samdze/playdate-nim#81]
The defauukt branch is the branch that is auto-selected for new PR's.

Please change that to dev as it is currently main, which nullifies the dev branch'es usefullness 

I don't have access, but here is were @samdze can change it:
![image](https://github.com/user-attachments/assets/2c7a3093-c1ed-461d-8de9-a57d7837d9e6)

**Comment by samdze** [comment]
I'm not sure but do you think it will also change the default branch the user will see when accessing the github page?
In this case the other goal of the dev branch would be undone

**Comment by samdze** [comment]
Yeah setting `dev` as the default branch makes it become the branch users will see when visiting the repository, this is not something we would want

**Comment by ninovanhooff** [comment]
Ah, a catch-22.

Allright, this can be closed
